# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TkeySign < Formula
  desc "Tool to digitally sign files with TKey"
  homepage "https://tillitis.se/"
  version "1.1.0"
  license "BSD-2-Clause"

  on_macos do
    url "https://github.com/tillitis/tkey-sign-cli/releases/download/v1.1.0/tkey-sign_1.1.0_Darwin_universal.tar.gz"
    sha256 "64209f76f0334e8243ae59550722d721a0eac2af46b23a376f41822ee5a1b169"

    define_method(:install) do
      bin.install "tkey-sign"
      man1.install "man/tkey-sign.1"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tillitis/tkey-sign-cli/releases/download/v1.1.0/tkey-sign_1.1.0_Linux_amd64.tar.gz"
      sha256 "a23fae531702ae4e9c7d0aaa27d050633f9519d07c61fa4992caad98b7ab45bf"
      define_method(:install) do
        bin.install "tkey-sign"
        man1.install "man/tkey-sign.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tillitis/tkey-sign-cli/releases/download/v1.1.0/tkey-sign_1.1.0_Linux_arm64.tar.gz"
      sha256 "c92c7d90398a80579077cd2d3d7336e21cdb1ed67cec52b1973ecc3850239331"
      define_method(:install) do
        bin.install "tkey-sign"
        man1.install "man/tkey-sign.1"
      end
    end
  end

  test do
    assert_match version.to_str, shell_output("#{bin}/tkey-sign --version 2>&1")
  end
end
