# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TkeySign < Formula
  desc "Tool to digitally sign files with TKey"
  homepage "https://tillitis.se/"
  version "0.0.8"
  license "GPLv2"

  on_macos do
    url "https://github.com/tillitis/tkey-sign-cli/releases/download/v0.0.8/tkey-sign_0.0.8_Darwin_universal.tar.gz"
    sha256 "3a1e2a184257fedc5d73aaf367c3f85a5dc1614e8859b3aa242e0e46e94a0c43"

    def install
      bin.install "tkey-sign"
      man1.install "man/tkey-sign.1"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tillitis/tkey-sign-cli/releases/download/v0.0.8/tkey-sign_0.0.8_Linux_arm64.tar.gz"
      sha256 "3a8a8dffed1c253c3f10e16dc45dd18bb228ae35f5c8f87c801c3f9debbaab3c"

      def install
        bin.install "tkey-sign"
        man1.install "man/tkey-sign.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tillitis/tkey-sign-cli/releases/download/v0.0.8/tkey-sign_0.0.8_Linux_amd64.tar.gz"
      sha256 "42d3538ba1d416dce837435d49bb9922b8892746dabf5557e7b6c7cf5fc1ae74"

      def install
        bin.install "tkey-sign"
        man1.install "man/tkey-sign.1"
      end
    end
  end

  test do
    assert_match version.to_str, shell_output("#{bin}/tkey-sign --version 2>&1")
  end
end
