# typed: false
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TkeyRunapp < Formula
  desc "Tool to load an application binary onto the TKey"
  homepage "https://tillitis.se/"
  version "0.0.3"
  license "BSD-2-Clause"

  on_macos do
    url "https://github.com/tillitis/tkey-devtools/releases/download/v0.0.3/tkey-runapp_0.0.3_Darwin_universal.tar.gz"
    sha256 "6bdf22890b1a125b80c9c3ae3b5c6eb3b11699e6d539b6b55933ce6c20dc8fae"

    define_method(:install) do
      bin.install "tkey-runapp"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tillitis/tkey-devtools/releases/download/v0.0.3/tkey-runapp_0.0.3_Linux_amd64.tar.gz"
      sha256 "0de3a35c62cac67f17c3a298ad4ddd4497d744445ab4b3ec0220efbef5817040"
      define_method(:install) do
        bin.install "tkey-runapp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tillitis/tkey-devtools/releases/download/v0.0.3/tkey-runapp_0.0.3_Linux_arm64.tar.gz"
      sha256 "871e6ae73d5281ca2d8398e74fb24c5b154dca64f0552efb2b8994ba9845c2c6"
      define_method(:install) do
        bin.install "tkey-runapp"
      end
    end
  end

  test do
    assert_match version.to_str, shell_output("#{bin}/tkey-runapp --version 2>&1")
  end
end
