# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TkeySign < Formula
  desc "Tool to digitally sign files with TKey"
  homepage "https://tillitis.se/"
  version "1.0.0"
  license "GPLv2"

  on_macos do
    url "https://github.com/tillitis/tkey-sign-cli/releases/download/v1.0.0/tkey-sign_1.0.0_Darwin_universal.tar.gz"
    sha256 "5a0045010543596971c5f2a4cfa666d61e7b6adc3e00a7433c7b8f4f3921a7d8"

    def install
      bin.install "tkey-sign"
      man1.install "man/tkey-sign.1"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tillitis/tkey-sign-cli/releases/download/v1.0.0/tkey-sign_1.0.0_Linux_arm64.tar.gz"
      sha256 "a15197ef6af5051fed2b723636b6c2ec9bf6cf6d903c78fff7965ed3a023f2ab"

      def install
        bin.install "tkey-sign"
        man1.install "man/tkey-sign.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tillitis/tkey-sign-cli/releases/download/v1.0.0/tkey-sign_1.0.0_Linux_amd64.tar.gz"
      sha256 "bbc45c28f7885d10baa7136b37885650122362b2125ab65608ca05fe0f8d26fd"

      def install
        bin.install "tkey-sign"
        man1.install "man/tkey-sign.1"
      end
    end
  end

  test do
    assert_match version.to_str, shell_output("#{bin}/tkey-sign --version 2>&1")
  end
end
