# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TkeyVerification < Formula
  desc "A program to sign or verify the identity of a Tillitis TKey."
  homepage "https://tillitis.se/"
  version "1.0.0"
  license "GPL-2.0-only"

  on_macos do
    url "https://github.com/tillitis/tkey-verification/releases/download/v1.0.0/tkey-verification_1.0.0_Darwin_universal.tar.gz"
    sha256 "50004f5b8e24e7343a68658630d04a4e140280109ff9ad320ca6da26cad4b12c"

    def install
      bin.install "tkey-verification"
      man1.install "man/tkey-verification.1"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tillitis/tkey-verification/releases/download/v1.0.0/tkey-verification_1.0.0_Linux_amd64.tar.gz"
        sha256 "5afc12007d486244d20e5a90678c1d320b5086e0600647fa7414824b5bf53412"

        def install
          bin.install "tkey-verification"
          man1.install "man/tkey-verification.1"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tillitis/tkey-verification/releases/download/v1.0.0/tkey-verification_1.0.0_Linux_arm64.tar.gz"
        sha256 "be3a5ada58b7062f43fff626077a4e6ca3851ae948723de45c3c78712d5969fc"

        def install
          bin.install "tkey-verification"
          man1.install "man/tkey-verification.1"
        end
      end
    end
  end
end

